# This jobs runs every day 2 hours after the nightly job for React Native so we can verify how the nightly is behaving.
name: Check Nightlies

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'website/**'
      - '.github/workflows/deploy-website.yml'
      - '.github/workflows/pr-check-new-entries.yml'
  workflow_dispatch:
  # nightly build @ 4:15 AM UTC
  schedule:
    - cron: '15 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  test-libraries:
    uses: ./.github/workflows/test-libraries-on-nightlies.yml
    secrets:
      discord_webhook_url: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK }}
      firebase_app_email: ${{ secrets.FIREBASE_APP_EMAIL }}
      firebase_app_pass: ${{ secrets.FIREBASE_APP_PASS }}
      firebase_app_projectname: ${{ secrets.FIREBASE_APP_PROJECTNAME }}
      firebase_app_apikey: ${{ secrets.FIREBASE_APP_APIKEY }}